name: Merge changes from main branch of repo-a to repo-b

on:
  push:
    branches:
      - main

jobs:
  merge_changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo-a
      uses: actions/checkout@v2

    - name: Ignore changes in .github folder and fstab.yaml
      run: git --no-pager diff --name-only HEAD^ HEAD | grep -v -e '^\.github/' -e '^fstab\.yaml$' > changes.txt

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git config --global credential.helper store

    - name: Obtain Personal Access Token
      run: echo "${{ secrets.GITHUB_TOKEN }}" > token.txt

    - name: Checkout repo-b
      run: |
        mkdir repo-b
        git -C repo-b init
        git -C repo-b remote add origin https://github.com/sukamat/repo-b.git
        git -C repo-b fetch --depth=1 origin main
        git -C repo-b checkout main

    - name: Apply changes to repo-b
      run: |
        cat changes.txt | xargs -I {} git -C repo-b apply --ignore-whitespace --exclude=.github/{}.patch

    - name: Push changes to repo-b
      run: |
        git -C repo-b add -A
        git -C repo-b commit -m "Merge changes from main branch of repo-a"
        cat token.txt | xargs -I {} git -C repo-b push origin main --quiet --set-upstream
