name: test-branch

on:
    push:
      branches:
        - stage
        - main
    workflow_dispatch:
      inputs:
        syncBranch:
          description: 'Branch to sync'
          required: true
          default: 'stage'
          type: choice
          options:
            - 'stage'
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Pick branch
              run: |
                echo ":heavy_minus_sign: Branch: $SYNC_BRANCH :heavy_check_mark:" | tee -a $GITHUB_STEP_SUMMARY
              env:
                  SYNC_BRANCH: ${{ inputs.syncBranch || github.ref_name }}

            - name: Checkout Repo
              uses: actions/checkout@v2
              with:
                persist-credentials: false
                ref: ${{ inputs.syncBranch || github.ref_name }}
