name: run z-sync

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      # - name: setup python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10' # install the python version needed

      - name: Set up Git
        run: |
          git config --global user.email "sukamat@adobe.com"
          git config --global user.name "Sunil Kamat"
      #     git config --global url.https://$GITHUB_TOKEN@github.com/.insteadOf https://github.com/          
      #     git remote set-url repob https://$GITHUB_TOKEN@github.com/sukamat/repo-b.git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ALL }}

      # - name: Test Git Authentication
      #   run: git ls-remote https://$GITHUB_TOKEN@github.com/sukamat/repo-b.git

      - name: Clone Reporting Repository
        run: |
          git clone https://$GITHUB_TOKEN@github.com/sukamat/repo-b.git
        if: always()

      - name: Run ls -la
        run: |
          ls -la          
        if: always()

      - name: Run rsync
        run: |
          echo "Running rsync"
          rsync -av --exclude='fstab.yaml' --exclude='.github' --exclude='.git' --exclude='.idea' ./ ../repo-b/
        if: always()

      - name: Commit and Push Changes
        run: |
          cd ../repo-b
          git status
          git add .
          git commit -m "Syncing repo-a to repo-b"
          git push origin main
        if: always()

#      - name: run sync.py
#        run: |
#          python .github/scripts/z-sync.py
