name: run floodgate repo sync

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.FG_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "repo-b,repo-c"

      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.email "${{ secrets.FG_SYNC_BOT_EMAIL }}"
          git config user.name "${{ secrets.FG_SYNC_BOT_NAME }}"

      - name: Clone Floodgate Repository
        run: |
          git clone https://github.com/sukamat/repo-b.git ../repo-b
          git clone https://github.com/sukamat/repo-c.git ../repo-c

      - name: Overwrite floodgate repo files with latest from source repo 
        run: |
          pwd
          ls -la
          echo "Running rsync"
          rsync -av --exclude='fstab.yaml' --exclude='.github' --exclude='.git' --exclude='.idea' ./ ../repo-b/
          rsync -av --exclude='fstab.yaml' --exclude='.github' --exclude='.git' --exclude='.idea' ./ ../repo-c/

      - name: Commit and Push Changes to Floodgate Repository
        run: |
          cd ../repo-b
          pwd
          ls -la
          git config user.email "${{ secrets.FG_SYNC_BOT_EMAIL }}"
          git config user.name "${{ secrets.FG_SYNC_BOT_NAME }}"
          echo "git status"
          git status
          echo "git remote set-url for repo-b"
          git remote set-url origin https://oauth2:$GITHUB_TOKEN@github.com/sukamat/repo-b.git
          echo "git remote -v"
          git remote -v
          echo "git add ."
          git add .
          echo "git commit -m 'Syncing repo-a to repo-b'"
          git commit -m "Syncing repo-a to repo-b"
          echo "git push"
          git push origin main

          cd ../repo-c
          pwd
          ls -la
          git config user.email "${{ secrets.FG_SYNC_BOT_EMAIL }}"
          git config user.name "${{ secrets.FG_SYNC_BOT_NAME }}"
          echo "git status"
          git status
          echo "git remote set-url for repo-c"
          git remote set-url origin https://oauth2:$GITHUB_TOKEN@github.com/sukamat/repo-c.git
          echo "git remote -v"
          git remote -v
          echo "git add ."
          git add .
          echo "git commit -m 'Syncing repo-a to repo-c'"
          git commit -m "Syncing repo-a to repo-c"
          echo "git push"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

          
        