name: run z-sync

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config user.email "sukamat@adobe.com"
          git config user.name "GitHub Actions"

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: run sync.py
        run: |          
          python .github/scripts/z-sync.py        
