name: run z-sync

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.FG_GITHUB_APP_PRIVATE_KEY }}
          permissions: write
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: Set up Git
        run: |
          git config --global user.email "sukamat@adobe.com"
          git config --global user.name "Sunil Kamat"
          git config --global url.https://${{ steps.generate_token.outputs.token }}@github.com/.insteadOf https://github.com/
          echo "${{ steps.generate_token.outputs.token }}" > token.txt
          echo "${{ env.GITHUB_TOKEN }}" > env.txt

      - name: Clone Reporting Repository
        run: |
          git clone https://github.com/sukamat/repo-b.git ../repo-b
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

      - name: Run ls -la
        run: |
          pwd
          ls -la

      - name: Run rsync
        run: |
          cat ../repo-a/token.txt
          cat ../repo-a/env.txt
          rm -f ../repo-a/token.txt
          rm -f ../repo-a/env.txt
          echo "Running rsync"
          rsync -av --exclude='fstab.yaml' --exclude='.github' --exclude='.git' --exclude='.idea' ./ ../repo-b/

      - name: Commit and Push Changes to repo-b
        run: |
          cd ../repo-b
          pwd
          ls -la
          echo "git status"
          git status
          echo "git remote -v"
          git remote -v
          echo "git add ."
          git add .
          echo "git commit -m 'Syncing repo-a to repo-b'"
          git commit -m "Syncing repo-a to repo-b"
          echo "git push origin main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
